databases:
  - name: financedb
    plan: free
    databaseName: financedb
    user: finances

services:
  - type: web
    plan: free
    name: finances
    runtime: python
    buildCommand: "./build.sh"
    # This is the key change - explicitly telling gunicorn where to find our WSGI application
    startCommand: "gunicorn --bind 0.0.0.0:$PORT config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
